// <auto-generated />
using System;
using FoodOrderingAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FoodOrderingAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260920044118_UpdateFoodImages")]
    partial class UpdateFoodImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.0");

            modelBuilder.Entity("FoodOrderingAPI.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Wood-fired and classic pizzas",
                            ImageUrl = "images/category-pizza.jpg",
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Juicy grilled and veg burgers",
                            ImageUrl = "images/category-burger.jpg",
                            Name = "Burgers"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Curries, biryani and more",
                            ImageUrl = "images/category-indian.jpg",
                            Name = "Indian"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Sweet endings to your meal",
                            ImageUrl = "images/category-dessert.jpg",
                            Name = "Desserts"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Cold drinks and shakes",
                            ImageUrl = "images/category-beverage.jpg",
                            Name = "Beverages"
                        });
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.FoodItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVeg")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("FoodItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "Classic cheese and tomato pizza",
                            ImageUrl = "https://loremflickr.com/400/300/margherita,pizza",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Margherita Pizza",
                            Price = 249.00m
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Loaded with garden veggies",
                            ImageUrl = "https://loremflickr.com/400/300/vegetable,pizza",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Farmhouse Pizza",
                            Price = 349.00m
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Description = "Spicy pepperoni with mozzarella",
                            ImageUrl = "https://loremflickr.com/400/300/pepperoni,pizza",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Pepperoni Pizza",
                            Price = 399.00m
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Crispy veg patty with fresh veggies",
                            ImageUrl = "https://loremflickr.com/400/300/veggie,burger",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Classic Veg Burger",
                            Price = 129.00m
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Description = "Crunchy fried chicken burger",
                            ImageUrl = "https://loremflickr.com/400/300/chicken,burger",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Zinger Burger",
                            Price = 179.00m
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Rich and creamy paneer curry",
                            ImageUrl = "https://loremflickr.com/400/300/paneer,curry",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Paneer Butter Masala",
                            Price = 259.00m
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Description = "Fragrant basmati rice with chicken",
                            ImageUrl = "https://loremflickr.com/400/300/biryani",
                            IsAvailable = true,
                            IsVeg = false,
                            Name = "Chicken Biryani",
                            Price = 289.00m
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Description = "Slow-cooked black lentils",
                            ImageUrl = "https://loremflickr.com/400/300/lentil,curry",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Dal Makhani",
                            Price = 219.00m
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 4,
                            Description = "Warm brownie with chocolate sauce",
                            ImageUrl = "https://loremflickr.com/400/300/chocolate,brownie",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Chocolate Brownie",
                            Price = 149.00m
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 4,
                            Description = "Soft milk dumplings in sugar syrup",
                            ImageUrl = "https://loremflickr.com/400/300/gulabjamun",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Gulab Jamun (2 pcs)",
                            Price = 99.00m
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 5,
                            Description = "Chilled coffee with ice cream",
                            ImageUrl = "https://loremflickr.com/400/300/icedcoffee",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Cold Coffee",
                            Price = 119.00m
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 5,
                            Description = "Refreshing spiced lemon drink",
                            ImageUrl = "https://loremflickr.com/400/300/lemonade",
                            IsAvailable = true,
                            IsVeg = true,
                            Name = "Masala Lemonade",
                            Price = 79.00m
                        });
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContactPhone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FoodItemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FoodItemName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.FoodItem", b =>
                {
                    b.HasOne("FoodOrderingAPI.Models.Category", "Category")
                        .WithMany("FoodItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.Order", b =>
                {
                    b.HasOne("FoodOrderingAPI.Models.Customer", "Customer")
                        .WithMany("Orders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.OrderItem", b =>
                {
                    b.HasOne("FoodOrderingAPI.Models.FoodItem", "FoodItem")
                        .WithMany()
                        .HasForeignKey("FoodItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FoodOrderingAPI.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FoodItem");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.Category", b =>
                {
                    b.Navigation("FoodItems");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.Customer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FoodOrderingAPI.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
